export const GET_COMMENTS = "GET_COMMENTS"
export const GET_COMMENTS_OK = "GET_COMMENTS_OK"
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL"

export const GET_SINGLE_COMMENT = "GET_SINGLE_POST"
export const GET_SINGLE_COMMENT_OK = "GET_SINGLE_POST_OK"
export const GET_SINGLE_COMMENT_FAIL = "GET_SINGLE_POST_FAIL"